SELECT 
    OFERTAS_SECUNDARIA.idModalidad, MODALIDAD.nomModalidad,
    OFERTAS_SECUNDARIA.idNivel, NIVEL.nomCiclo,
    OFERTAS_SECUNDARIA.idPlan, PLAN.nomPlan,
    OFERTAS_SECUNDARIA.idTurnoL, TURNOL.nomTurno,
    OFERTAS_SECUNDARIA.idOpcion, OPCION.nomOpcion,
    OFERTAS_SECUNDARIA.idUbicacion, UBICACION.nomDepartamento, UBICACION.nomZonaPais,
    COUNT(DISTINCT idLiceo) AS cantLiceos
FROM OFERTAS_SECUNDARIA JOIN MODALIDAD ON OFERTAS_SECUNDARIA.idModalidad = MODALIDAD.idModalidad
JOIN NIVEL ON OFERTAS_SECUNDARIA.idNivel = NIVEL.idGrado
JOIN PLAN ON OFERTAS_SECUNDARIA.idPlan = PLAN.idPlan
JOIN TURNOL ON OFERTAS_SECUNDARIA.idTurnoL = TURNOL.idTurno
JOIN OPCION ON OFERTAS_SECUNDARIA.idOpcion = OPCION.idOpcion
JOIN UBICACION ON OFERTAS_SECUNDARIA.idUbicacion = UBICACION.IDUBICACION
WHERE 
GROUP BY OFERTAS_SECUNDARIA.idModalidad, MODALIDAD.nomModalidad,
    OFERTAS_SECUNDARIA.idNivel, NIVEL.nomCiclo,
    OFERTAS_SECUNDARIA.idPlan, PLAN.nomPlan,
    OFERTAS_SECUNDARIA.idTurnoL, TURNOL.nomTurno,
    OFERTAS_SECUNDARIA.idOpcion, OPCION.nomOpcion,
    OFERTAS_SECUNDARIA.idUbicacion, UBICACION.nomDepartamento, UBICACION.nomZonaPais


-- Testing

-- Para cada zonapais, indicar la cantidad de liceos
SELECT nomZonaPais, COUNT(DISTINCT idLiceo) AS cantLiceos
FROM UBICACION JOIN OFERTAS_SECUNDARIA ON UBICACION.IDUBICACION = OFERTAS_SECUNDARIA.idUbicacion
GROUP BY nomZonaPais;