-- REQUERIMIENTO 1

CREATE TABLE LICEO (
    IDLICEO INTEGER PRIMARY KEY,
    nomLiceo VARCHAR(200) NOT NULL
);

CREATE TABLE MODALIDAD (
    IDMODALIDAD INTEGER PRIMARY KEY,
    nomModalidad VARCHAR(50) NOT NULL
);

CREATE TABLE NIVEL (
    idGrado INTEGER PRIMARY KEY,
    idCiclo INTEGER NOT NULL,
    nomCiclo VARCHAR(200) NOT NULL
);

CREATE TABLE OPCION (
    IDOPCION INTEGER PRIMARY KEY,
    nomOpcion VARCHAR(50)
);

CREATE TABLE PLAN (
    IDPLAN INTEGER PRIMARY KEY,
    nomPlan VARCHAR(200) NOT NULL,
    idEpoca INTEGER NOT NULL,
    nomEpoca VARCHAR(200) NOT NULL,
    idEsNuevo INTEGER NOT NULL,
    esNuevo VARCHAR(200) NOT NULL,
    idFranjaEdad INTEGER NOT NULL,
    franjaEdad VARCHAR(200) NOT NULL
);

CREATE TABLE TURNOL(
    IDTURNO INTEGER PRIMARY KEY,
    nomTurno VARCHAR(50) NOT NULL,
    idHorario INTEGER NOT NULL,
    nomHorario VARCHAR(50) NOT NULL,
    idFranjaHoraria INTEGER NOT NULL,
    franjaHoraria VARCHAR(50) NOT NULL
);

CREATE TABLE UBICACION (
    IDUBICACION INTEGER PRIMARY KEY,
    latitud FLOAT,
    longitud FLOAT,
    idArea INTEGER,
    nomArea VARCHAR(200),
    idBarrio INTEGER,
    nomBarrio VARCHAR(200),
    idZona INTEGER,
    nomZona VARCHAR(200), 
    idLocalidad INTEGER NOT NULL,
    nomLocalidad VARCHAR(200) NOT NULL,
    idDepartamento INTEGER NOT NULL,
    nomDepartamento VARCHAR(200) NOT NULL,
    idZonaPais INTEGER NOT NULL,
    nomZonaPais VARCHAR(200) NOT NULL
);

-- REQUERIMIENTO 2

CREATE TABLE ESCUELA(
    IDESCUELA INTEGER PRIMARY KEY,
    nomEscuela VARCHAR(200) NOT NULL,
    idTipo INTEGER NOT NULL,
    nomTipo VARCHAR(200) NOT NULL
);

CREATE TABLE TURNOE(
    idTurno INTEGER PRIMARY KEY,
    nomTurno VARCHAR(50) NOT NULL,
    idTipoTurno INTEGER NOT NULL,
    nomTipoTurno VARCHAR(50) NOT NULL,
    idFranjaHoraria INTEGER NOT NULL,
    franjaHoraria VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIA(
    idCategoria INTEGER PRIMARY KEY,
    nomCategoria VARCHAR(50) NOT NULL,
    idPractica INTEGER NOT NULL,
    nomPractica VARCHAR(50) NOT NULL,
    idDiscapacidad INTEGER NOT NULL,
    nomDiscapacidad VARCHAR(50) NOT NULL
);

CREATE TABLE NIVELE(
    idNivel INTEGER PRIMARY KEY,
    nomNivel VARCHAR(200),
    idCiclo INTEGER NOT NULL,
    nomCiclo VARCHAR(200)
);


CREATE TABLE UBICACIONE (
    IDUBICACION INTEGER PRIMARY KEY,
    latitud FLOAT, -- lo tengo
    longitud FLOAT, -- lo tengo
    idArea INTEGER,
    nomArea VARCHAR(200),
    idBarrio INTEGER,
    nomBarrio VARCHAR(200),
    idZona INTEGER, -- lo tengo
    nomZona VARCHAR(200), 
    idLocalidad INTEGER NOT NULL,-- lo tengo
    nomLocalidad VARCHAR(200) NOT NULL,-- lo tengo
    idDepartamento INTEGER NOT NULL,-- lo tengo
    nomDepartamento VARCHAR(200) NOT NULL,-- lo tengo
    idZonaPais INTEGER NOT NULL,-- lo tengo
    nomZonaPais VARCHAR(200) NOT NULL -- lo tengo
);
-- tablas de hechos

CREATE TABLE OFERTAS_SECUNDARIA(
    idLiceo INTEGER NOT NULL,
    idModalidad INTEGER NOT NULL,
    idNivel INTEGER NOT NULL,
    idPlan INTEGER NOT NULL,
    idTurnoL INTEGER NOT NULL,
    idOpcion INTEGER NOT NULL,
    idUbicacion INTEGER NOT NULL,
    porcLiceos FLOAT
);
CREATE TABLE OFERTAS_INICIAL_PRIMARIA(
    idEscuela INTEGER NOT NULL,
    idTurnoE INTEGER NOT NULL,
    idCategoria INTEGER NOT NULL,
    idNivelDesde INTEGER NOT NULL,
    idNivelHasta INTEGER NOT NULL,
    idUbicacion INTEGER NOT NULL,
    cant_aulas INTEGER,
    gruposXnivel INTEGER,
    cant_niveles Integer
);



-- primary keys

ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT PK_OFERTAS_SECUNDARIA PRIMARY KEY (idLiceo, idModalidad, idNivel, idPlan, idTurnoL, idOpcion, idUbicacion);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT PK_OFERTAS_INICIAL_PRIMARIA PRIMARY KEY (idEscuela, idTurnoE, idCategoria, idNivelDesde, idNivelHasta, idUbicacion);

-- foreign keys

ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_LICEO FOREIGN KEY (idLiceo) REFERENCES LICEO(IDLICEO);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_MODALIDAD FOREIGN KEY (idModalidad) REFERENCES MODALIDAD(IDMODALIDAD);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_NIVEL FOREIGN KEY (idNivel) REFERENCES NIVEL(idGrado);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_PLAN FOREIGN KEY (idPlan) REFERENCES PLAN(IDPLAN);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_TURNO FOREIGN KEY (idTurnoL) REFERENCES TURNOL(IDTURNO);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_OPCION FOREIGN KEY (idOpcion) REFERENCES OPCION(IDOPCION);
ALTER TABLE OFERTAS_SECUNDARIA ADD CONSTRAINT FK_OFERTAS_SECUNDARIA_UBICACION FOREIGN KEY (idUbicacion) REFERENCES UBICACION(IDUBICACION);

ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_ESCUELA FOREIGN KEY (idEscuela) REFERENCES ESCUELA(IDESCUELA);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_TURNO FOREIGN KEY (idTurnoE) REFERENCES TURNOE(idTurno);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_NIVELD FOREIGN KEY (idNivelDesde) REFERENCES NIVELE(idNivel);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_NIVELH FOREIGN KEY (idNivelHasta) REFERENCES NIVELE(idNivel);
ALTER TABLE OFERTAS_INICIAL_PRIMARIA ADD CONSTRAINT FK_OFERTAS_INICIAL_PRIMARIA_UBICACIONE FOREIGN KEY (idUbicacion) REFERENCES UBICACIONE(IDUBICACION);


---
-- medidas
ALTER TABLE OFERTAS_SECUNDARIA
ADD COLUMN cant_ofertas integer DEFAULT 1;
ALTER TABLE OFERTAS_SECUNDARIA
ADD COLUMN cant_liceos INTEGER DEFAULT 1;

-- remove null restriction on 
-- table NIVELE on fields
-- nomNivel and nomCiclo
ALTER TABLE NIVELE
ALTER COLUMN nomNivel DROP NOT NULL;